// - NOTIFICATION
export const SHOW_POPUP_NOTIFICATION = 'SHOW_POPUP_NOTIFICATION';
export const HIDE_POPUP_NOTIFICATION = 'HIDE_POPUP_NOTIFICATION';
//APPLICATION
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
// AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

